# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rx7aCYBrRDZuMRxdka4vcXkf-HCphumb
"""

# Dua ra tong so huy chuong vang bac dong
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data_huy_chuong = data.drop(['Sport','City', 'Year', 'Discipline', 'Event','Event gender' ], axis = 1)
data_huy_chuong.groupby('Medal').count()


#--------------------------------------------------------------------------------------------#


# Dua ra xep hang 3 quoc gia so huu huy chuong vang nhieu nhat
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
# - Xoa cac cot khong can thiet
data_huy_chuong = data.drop(['Sport','City', 'Year', 'Discipline', 'Event','Event gender' ], axis = 1)
# - Dua ra danh sach chi ton tai huy chuong vang
Gold = data_huy_chuong[data_huy_chuong['Medal'] == 'Gold']
# - Group lai va cho dem so luong huy chuong cua moi nuoc
Gold_NOC = Gold.groupby('NOC').count()
# - Sap xep theo thu tu giam dan so luong huy chuong vang
Gold_NOC = Gold_NOC.sort_values('Medal', ascending=False)
# - Dua ra 3 Quoc Gia co huy chuong vang nhieu nhat
Gold_NOC.head(3)


#--------------------------------------------------------------------------------------------#


# Dua ra cac Event trong 1 mon the thao cu the. Vd o day la: Skatting
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
# Loc du lieu tu data, chi lay Sport vs Event
data_Sport = data[["Event", "Sport"]]
# Chon 1 mon the thao cu the de loc ra. O day la: Skatting
Skatting = data_Sport[data_Sport['Sport'] == 'Skating']
# Dua ra cac Event co trong Skating
Skatting['Event'].unique()


#--------------------------------------------------------------------------------------------#


# Dua ra cac mon the thao trong tung nam 
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data_1 = data[['Year', 'Sport']]
data_year = data_1['Year'].unique()
c = []
a = []
for i in data_year:
  a = data_1[data_1['Year']== i]
  b = a['Sport'].unique()
  c.append(b)
for n in range(len(c[0]) + len(c[0][0])):  
  print('Nam ')
  print(data_year[n])
  print(c[n])

